export const theme = {
  color: {
    primary: '#fff',
    primaryDark: '#e8eaed',
    primaryTransparent: 'hsla(0, 100%, 100%, 0.5)',
    // Black
    contrast: '#2D2D2F',
    contrastTransparent: ' hsla(240, 2%, 18%, 0.75)',
    contrastLightHover: '#3D3D3F',
    contrastDarkHover: '#1D1D1F',
    // Blue
    accentPrimary: '#79C9EC',
    accentPrimaryLighter: '#89D9FC',
    accentPrimaryDarker: '#115A78',
    accentPrimaryDarkerLightHover: '#176c8f',
    // Pink
    accentSecondary: '#FE9FBF',
    accentSecondaryDarker: '#BF3160',
    // Error
    error: 'red',
    errorTransparent: 'hsla(0, 100%, 50%, 0.05)',
    // Border dividers
    borderDivider: '#ccc',
  },
  fontSize: {
    pageHeadingRegular: '100rem',
    sectionHeading: '100rem',
    textXS: '0.75rem',
    textSM: '0.875rem',
    textBase: '1rem',
    textLG: '1.125rem',
    textXL: '1.25rem',
    text2XL: '1.5rem',
    text3XL: '1.875rem',
    text4XL: '2.25rem',
    text5XL: '3rem',
    text6XL: '3.75rem',
    text7XL: '4.5rem',
    text8XL: '6rem',
    text9XL: '8rem',
  },
  lineHeight: {
    pageHeadingRegular: '100rem',
    sectionHeading: '100rem',
    textXS: '1rem',
    textSM: '1.25rem',
    textBase: '1.5rem',
    textLG: '1.75rem',
    textXL: '1.75rem',
    text2XL: '2rem',
    text3XL: '2.25rem',
    text4XL: '2.5rem',
    text5XL: '2.75rem',
    text6XL: '3rem',
    text7XL: '1',
    text8XL: '1',
    text9XL: '1',
  },
};
