export const theme = {
  color: {
    black: '#000',
    white: '#fff',
    text: {
      primary: '#2D2D2F',
      primaryLightHover: '#3D3D3F',
      primaryDarkHover: '#1D1D1F',
      accentPrimary: '#BF3160',
      accentSecondary: '#2D79D6',
      accentSecondaryLightHover: '#5693de',
      accentTertiary: '#115A78',
      accentTertiaryLightHover: '#146d91',
    },
    icons: {
      primary: '#FE9FBF',
      closeNav: '#2D2D2F',
    },
    button: {
      formSubmit: '#79C9EC',
      formSubmitHover: '#89D9FC',
    },
    input: {
      invalidBorder: 'red',
      invailidBackground: 'hsla(0, 100%, 50%, 0.05)',
    },
    background: {
      staffSection: '#e8eaed',
      nurserySection: '#79C9EC',
      imageTransparentHover: 'hsla(0, 100%, 100%, 0.1)',
    },
    pageErrorTheme: '#115A78',
  },
  fontSize: {
    pageHeadingRegular: '100rem',
    sectionHeading: '100rem',
    textXS: '0.75rem',
    textSM: '0.875rem',
    textBase: '1rem',
    textLG: '1.125rem',
    textXL: '1.25rem',
    text2XL: '1.5rem',
    text3XL: '1.875rem',
    text4XL: '2.25rem',
    text5XL: '3rem',
    text6XL: '3.75rem',
    text7XL: '4.5rem',
    text8XL: '6rem',
    text9XL: '8rem',
  },
  lineHeight: {
    pageHeadingRegular: '100rem',
    sectionHeading: '100rem',
    textXS: '1rem',
    textSM: '1.25rem',
    textBase: '1.5rem',
    textLG: '1.75rem',
    textXL: '1.75rem',
    text2XL: '2rem',
    text3XL: '2.25rem',
    text4XL: '2.5rem',
    text5XL: '1',
    text6XL: '1',
    text7XL: '1',
    text8XL: '1',
    text9XL: '1',
  },
};
